import { ref } from 'vue'
import { defineStore } from 'pinia'
import type { DeviceNode } from '@/types/device'
import { getDeviceTreeData, transformDeviceTreeData, type DeviceTreeResponse } from '@/api/modules/deviceTree'

export const useDeviceTreeStore = defineStore('deviceTree', () => {
  // 设备树数据
  const deviceTreeData = ref<DeviceNode[]>([])
  
  // 加载状态
  const loading = ref(false)
  
  // 使用静态假数据初始化设备树
  const initializeDeviceTreeData = () => {
    const mockData: DeviceTreeResponse = {
      "code": 200,
      "message": "success",
      "data": {
        "factories": [
          {
            "factoryId": "factory_001",
            "factoryName": "厂区",
            "factoryCode": "FACTORY_MAIN",
            "totalDeviceCount": 12,
            "totalPointCount": 24,
            "onlineDeviceCount": 12,
            "alarmDeviceCount": 2,
            "workshops": [
              {
                "workshopId": "workshop_001",
                "workshopName": "车间A",
                "workshopCode": "WORKSHOP_A",
                "status": "normal",
                "deviceCount": 3,
                "pointCount": 6,
                "onlineCount": 3,
                "alarmCount": 0,
                "devices": [
                  {
                    "deviceId": "device_001",
                    "deviceName": "设备a",
                    "deviceCode": "DEV_A_001",
                    "deviceType": "motor",
                    "deviceTypeName": "电机",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "MOTOR-1000X",
                    "manufacturer": "厂家A",
                    "lastDataTime": "2025-12-12 12:09:00",
                    "points": [
                      {
                        "pointId": "point_001",
                        "pointName": "点位1",
                        "pointCode": "POINT_001",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "驱动端水平",
                        "status": "normal",
                        "currentValue": 12.5,
                        "unit": "mm/s",
                        "thresholdWarning": 10.0,
                        "thresholdAlarm": 15.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_002",
                        "pointName": "点位2",
                        "pointCode": "POINT_002",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "轴承座",
                        "status": "normal",
                        "currentValue": 65.3,
                        "unit": "°C",
                        "thresholdWarning": 70.0,
                        "thresholdAlarm": 80.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_003",
                        "pointName": "点位3",
                        "pointCode": "POINT_003",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-300",
                        "position": "出口",
                        "status": "warning",
                        "currentValue": 1.2,
                        "unit": "MPa",
                        "thresholdWarning": 1.0,
                        "thresholdAlarm": 1.5,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_004",
                        "pointName": "点位4",
                        "pointCode": "POINT_004",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-400",
                        "position": "管道",
                        "status": "normal",
                        "currentValue": 45.6,
                        "unit": "m³/h",
                        "thresholdWarning": 40.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_005",
                        "pointName": "点位5",
                        "pointCode": "POINT_005",
                        "pointType": "speed",
                        "pointTypeName": "转速监测点",
                        "sensorModel": "SS-500",
                        "position": "轴端",
                        "status": "normal",
                        "currentValue": 1480,
                        "unit": "rpm",
                        "thresholdWarning": 1500,
                        "thresholdAlarm": 1600,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_006",
                        "pointName": "点位6",
                        "pointCode": "POINT_006",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "自由端垂直",
                        "status": "normal",
                        "currentValue": 8.2,
                        "unit": "mm/s",
                        "thresholdWarning": 10.0,
                        "thresholdAlarm": 15.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_007",
                        "pointName": "点位7",
                        "pointCode": "POINT_007",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "外壳",
                        "status": "normal",
                        "currentValue": 72.1,
                        "unit": "°C",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_008",
                        "pointName": "点位8",
                        "pointCode": "POINT_008",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "设备表面",
                        "status": "normal",
                        "currentValue": 78.5,
                        "unit": "dB",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_009",
                        "pointName": "点位9",
                        "pointCode": "POINT_009",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "周围环境",
                        "status": "normal",
                        "currentValue": 45.2,
                        "unit": "%RH",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 70.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      },
                      {
                        "pointId": "point_010",
                        "pointName": "点位10",
                        "pointCode": "POINT_010",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "轴向",
                        "status": "alarm",
                        "currentValue": 18.7,
                        "unit": "mm/s",
                        "thresholdWarning": 10.0,
                        "thresholdAlarm": 15.0,
                        "lastUpdateTime": "2025-12-12 12:09:00"
                      }
                    ]
                  },
                  {
                    "deviceId": "device_002",
                    "deviceName": "设备b",
                    "deviceCode": "DEV_A_002",
                    "deviceType": "pump",
                    "deviceTypeName": "泵",
                    "status": "alarm",
                    "onlineStatus": "online",
                    "model": "PUMP-500",
                    "manufacturer": "厂家B",
                    "lastDataTime": "2025-12-12 12:08:00",
                    "points": [
                      {
                        "pointId": "point_003",
                        "pointName": "点位1",
                        "pointCode": "POINT_003",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "泵体上方",
                        "status": "warning",
                        "currentValue": 92.5,
                        "unit": "dB",
                        "thresholdWarning": 90.0,
                        "thresholdAlarm": 100.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_004",
                        "pointName": "点位2",
                        "pointCode": "POINT_004",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "泵体水平",
                        "status": "normal",
                        "currentValue": 8.2,
                        "unit": "mm/s",
                        "thresholdWarning": 10.0,
                        "thresholdAlarm": 15.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_005",
                        "pointName": "点位3",
                        "pointCode": "POINT_005",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-300",
                        "position": "出口",
                        "status": "warning",
                        "currentValue": 1.2,
                        "unit": "MPa",
                        "thresholdWarning": 1.0,
                        "thresholdAlarm": 1.5,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_006",
                        "pointName": "点位4",
                        "pointCode": "POINT_006",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-400",
                        "position": "管道",
                        "status": "normal",
                        "currentValue": 45.6,
                        "unit": "m³/h",
                        "thresholdWarning": 40.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_007",
                        "pointName": "点位5",
                        "pointCode": "POINT_007",
                        "pointType": "speed",
                        "pointTypeName": "转速监测点",
                        "sensorModel": "SS-500",
                        "position": "轴端",
                        "status": "normal",
                        "currentValue": 1480,
                        "unit": "rpm",
                        "thresholdWarning": 1500,
                        "thresholdAlarm": 1600,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_008",
                        "pointName": "点位6",
                        "pointCode": "POINT_008",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "自由端垂直",
                        "status": "normal",
                        "currentValue": 8.2,
                        "unit": "mm/s",
                        "thresholdWarning": 10.0,
                        "thresholdAlarm": 15.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_009",
                        "pointName": "点位7",
                        "pointCode": "POINT_009",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "外壳",
                        "status": "normal",
                        "currentValue": 72.1,
                        "unit": "°C",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_010",
                        "pointName": "点位8",
                        "pointCode": "POINT_010",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "设备表面",
                        "status": "normal",
                        "currentValue": 78.5,
                        "unit": "dB",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_011",
                        "pointName": "点位9",
                        "pointCode": "POINT_011",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "周围环境",
                        "status": "normal",
                        "currentValue": 45.2,
                        "unit": "%RH",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 70.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      },
                      {
                        "pointId": "point_012",
                        "pointName": "点位10",
                        "pointCode": "POINT_012",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "轴向",
                        "status": "alarm",
                        "currentValue": 18.7,
                        "unit": "mm/s",
                        "thresholdWarning": 10.0,
                        "thresholdAlarm": 15.0,
                        "lastUpdateTime": "2025-12-12 12:08:00"
                      }
                    ]
                  },
                  {
                    "deviceId": "device_003",
                    "deviceName": "设备c",
                    "deviceCode": "DEV_A_003",
                    "deviceType": "compressor",
                    "deviceTypeName": "压缩机",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "COMP-2000",
                    "manufacturer": "厂家C",
                    "lastDataTime": "2025-12-12 12:07:00",
                    "points": [
                      {
                        "pointId": "point_007",
                        "pointName": "点位1",
                        "pointCode": "POINT_007",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-300",
                        "position": "进气口",
                        "status": "normal",
                        "currentValue": 0.65,
                        "unit": "MPa",
                        "thresholdWarning": 0.7,
                        "thresholdAlarm": 0.8,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_008",
                        "pointName": "点位2",
                        "pointCode": "POINT_008",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-250",
                        "position": "排气口",
                        "status": "normal",
                        "currentValue": 85.2,
                        "unit": "°C",
                        "thresholdWarning": 90.0,
                        "thresholdAlarm": 100.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_009",
                        "pointName": "点位3",
                        "pointCode": "POINT_009",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "驱动端水平",
                        "status": "normal",
                        "currentValue": 6.8,
                        "unit": "mm/s",
                        "thresholdWarning": 8.0,
                        "thresholdAlarm": 12.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_010",
                        "pointName": "点位4",
                        "pointCode": "POINT_010",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-400",
                        "position": "管道",
                        "status": "normal",
                        "currentValue": 38.5,
                        "unit": "m³/h",
                        "thresholdWarning": 40.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_011",
                        "pointName": "点位5",
                        "pointCode": "POINT_011",
                        "pointType": "speed",
                        "pointTypeName": "转速监测点",
                        "sensorModel": "SS-500",
                        "position": "轴端",
                        "status": "normal",
                        "currentValue": 1250,
                        "unit": "rpm",
                        "thresholdWarning": 1300,
                        "thresholdAlarm": 1400,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_012",
                        "pointName": "点位6",
                        "pointCode": "POINT_012",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "自由端垂直",
                        "status": "warning",
                        "currentValue": 10.5,
                        "unit": "mm/s",
                        "thresholdWarning": 8.0,
                        "thresholdAlarm": 12.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_013",
                        "pointName": "点位7",
                        "pointCode": "POINT_013",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "外壳",
                        "status": "normal",
                        "currentValue": 68.3,
                        "unit": "°C",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_014",
                        "pointName": "点位8",
                        "pointCode": "POINT_014",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "设备表面",
                        "status": "normal",
                        "currentValue": 75.8,
                        "unit": "dB",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_015",
                        "pointName": "点位9",
                        "pointCode": "POINT_015",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "周围环境",
                        "status": "normal",
                        "currentValue": 42.6,
                        "unit": "%RH",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 70.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_016",
                        "pointName": "点位10",
                        "pointCode": "POINT_016",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "轴向",
                        "status": "normal",
                        "currentValue": 7.2,
                        "unit": "mm/s",
                        "thresholdWarning": 8.0,
                        "thresholdAlarm": 12.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      }
                    ]
                  }
                ]
              },
              {
                "workshopId": "workshop_002",
                "workshopName": "车间B",
                "workshopCode": "WORKSHOP_B",
                "status": "normal",
                "deviceCount": 3,
                "pointCount": 6,
                "onlineCount": 3,
                "alarmCount": 0,
                "devices": [
                  {
                    "deviceId": "device_004",
                    "deviceName": "设备d",
                    "deviceCode": "DEV_B_001",
                    "deviceType": "fan",
                    "deviceTypeName": "风机",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "FAN-800",
                    "manufacturer": "厂家C",
                    "lastDataTime": "2025-12-12 12:07:00",
                    "points": [
                      {
                        "pointId": "point_009",
                        "pointName": "点位1",
                        "pointCode": "POINT_009",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "风机轴承",
                        "status": "normal",
                        "currentValue": 6.5,
                        "unit": "mm/s",
                        "thresholdWarning": 8.0,
                        "thresholdAlarm": 12.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_010",
                        "pointName": "点位2",
                        "pointCode": "POINT_010",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-100",
                        "position": "电机外壳",
                        "status": "normal",
                        "currentValue": 45.8,
                        "unit": "°C",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 75.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_011",
                        "pointName": "点位3",
                        "pointCode": "POINT_011",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-200",
                        "position": "风机进风口",
                        "status": "normal",
                        "currentValue": 72.3,
                        "unit": "dB",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_012",
                        "pointName": "点位4",
                        "pointCode": "POINT_012",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-300",
                        "position": "风道",
                        "status": "normal",
                        "currentValue": 0.85,
                        "unit": "Pa",
                        "thresholdWarning": 1.0,
                        "thresholdAlarm": 1.2,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_013",
                        "pointName": "点位5",
                        "pointCode": "POINT_013",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-400",
                        "position": "风管",
                        "status": "normal",
                        "currentValue": 120.5,
                        "unit": "m³/h",
                        "thresholdWarning": 130.0,
                        "thresholdAlarm": 150.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_014",
                        "pointName": "点位6",
                        "pointCode": "POINT_014",
                        "pointType": "speed",
                        "pointTypeName": "转速监测点",
                        "sensorModel": "SS-500",
                        "position": "风机轴",
                        "status": "normal",
                        "currentValue": 1150,
                        "unit": "rpm",
                        "thresholdWarning": 1200,
                        "thresholdAlarm": 1300,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_015",
                        "pointName": "点位7",
                        "pointCode": "POINT_015",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "周围环境",
                        "status": "normal",
                        "currentValue": 48.2,
                        "unit": "%RH",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 70.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_016",
                        "pointName": "点位8",
                        "pointCode": "POINT_016",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "电机轴承",
                        "status": "warning",
                        "currentValue": 9.2,
                        "unit": "mm/s",
                        "thresholdWarning": 8.0,
                        "thresholdAlarm": 12.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_017",
                        "pointName": "点位9",
                        "pointCode": "POINT_017",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "风机出风口",
                        "status": "normal",
                        "currentValue": 70.1,
                        "unit": "dB",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      },
                      {
                        "pointId": "point_018",
                        "pointName": "点位10",
                        "pointCode": "POINT_018",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-250",
                        "position": "风机外壳",
                        "status": "normal",
                        "currentValue": 65.3,
                        "unit": "°C",
                        "thresholdWarning": 70.0,
                        "thresholdAlarm": 80.0,
                        "lastUpdateTime": "2025-12-12 12:07:00"
                      }
                    ]
                  },
                  {
                    "deviceId": "device_005",
                    "deviceName": "设备e",
                    "deviceCode": "DEV_B_002",
                    "deviceType": "conveyor",
                    "deviceTypeName": "传送带",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "CONV-150",
                    "manufacturer": "厂家D",
                    "lastDataTime": "2025-12-12 12:06:00",
                    "points": [
                      {
                        "pointId": "point_011",
                        "pointName": "点位1",
                        "pointCode": "POINT_011",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-150",
                        "position": "驱动轮",
                        "status": "normal",
                        "currentValue": 4.2,
                        "unit": "mm/s",
                        "thresholdWarning": 5.0,
                        "thresholdAlarm": 8.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_012",
                        "pointName": "点位2",
                        "pointCode": "POINT_012",
                        "pointType": "speed",
                        "pointTypeName": "速度监测点",
                        "sensorModel": "SS-100",
                        "position": "电机输出轴",
                        "status": "normal",
                        "currentValue": 1485,
                        "unit": "rpm",
                        "thresholdWarning": 1500,
                        "thresholdAlarm": 1600,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_013",
                        "pointName": "点位3",
                        "pointCode": "POINT_013",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "电机",
                        "status": "normal",
                        "currentValue": 65.2,
                        "unit": "°C",
                        "thresholdWarning": 70.0,
                        "thresholdAlarm": 80.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_014",
                        "pointName": "点位4",
                        "pointCode": "POINT_014",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "传送带",
                        "status": "warning",
                        "currentValue": 85.6,
                        "unit": "dB",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_015",
                        "pointName": "点位5",
                        "pointCode": "POINT_015",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-300",
                        "position": "输送通道",
                        "status": "normal",
                        "currentValue": 1.2,
                        "unit": "MPa",
                        "thresholdWarning": 1.5,
                        "thresholdAlarm": 2.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_016",
                        "pointName": "点位6",
                        "pointCode": "POINT_016",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-400",
                        "position": "冷却系统",
                        "status": "normal",
                        "currentValue": 25.8,
                        "unit": "m³/h",
                        "thresholdWarning": 30.0,
                        "thresholdAlarm": 40.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_017",
                        "pointName": "点位7",
                        "pointCode": "POINT_017",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "工作环境",
                        "status": "normal",
                        "currentValue": 52.3,
                        "unit": "%RH",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 70.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_018",
                        "pointName": "点位8",
                        "pointCode": "POINT_018",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "从动轮",
                        "status": "normal",
                        "currentValue": 3.8,
                        "unit": "mm/s",
                        "thresholdWarning": 5.0,
                        "thresholdAlarm": 8.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_019",
                        "pointName": "点位9",
                        "pointCode": "POINT_019",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-250",
                        "position": "减速机",
                        "status": "normal",
                        "currentValue": 72.5,
                        "unit": "°C",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      },
                      {
                        "pointId": "point_020",
                        "pointName": "点位10",
                        "pointCode": "POINT_020",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-200",
                        "position": "防护罩",
                        "status": "normal",
                        "currentValue": 78.2,
                        "unit": "dB",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:06:00"
                      }
                    ]
                  },
                  {
                    "deviceId": "device_006",
                    "deviceName": "设备f",
                    "deviceCode": "DEV_B_003",
                    "deviceType": "boiler",
                    "deviceTypeName": "锅炉",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "BOIL-300",
                    "manufacturer": "厂家E",
                    "lastDataTime": "2025-12-12 12:05:00",
                    "points": [
                      {
                        "pointId": "point_013",
                        "pointName": "点位1",
                        "pointCode": "POINT_013",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-300",
                        "position": "炉膛",
                        "status": "normal",
                        "currentValue": 850.5,
                        "unit": "°C",
                        "thresholdWarning": 880.0,
                        "thresholdAlarm": 900.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_014",
                        "pointName": "点位2",
                        "pointCode": "POINT_014",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-200",
                        "position": "蒸汽出口",
                        "status": "normal",
                        "currentValue": 1.25,
                        "unit": "MPa",
                        "thresholdWarning": 1.3,
                        "thresholdAlarm": 1.5,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_015",
                        "pointName": "点位3",
                        "pointCode": "POINT_015",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-400",
                        "position": "给水管道",
                        "status": "normal",
                        "currentValue": 45.2,
                        "unit": "t/h",
                        "thresholdWarning": 50.0,
                        "thresholdAlarm": 60.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_016",
                        "pointName": "点位4",
                        "pointCode": "POINT_016",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "鼓风机",
                        "status": "warning",
                        "currentValue": 9.8,
                        "unit": "mm/s",
                        "thresholdWarning": 8.0,
                        "thresholdAlarm": 12.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_017",
                        "pointName": "点位5",
                        "pointCode": "POINT_017",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "锅炉本体",
                        "status": "normal",
                        "currentValue": 82.3,
                        "unit": "dB",
                        "thresholdWarning": 85.0,
                        "thresholdAlarm": 95.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_018",
                        "pointName": "点位6",
                        "pointCode": "POINT_018",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "烟气管道",
                        "status": "normal",
                        "currentValue": 15.6,
                        "unit": "%RH",
                        "thresholdWarning": 20.0,
                        "thresholdAlarm": 30.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_019",
                        "pointName": "点位7",
                        "pointCode": "POINT_019",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-250",
                        "position": "省煤器",
                        "status": "normal",
                        "currentValue": 320.8,
                        "unit": "°C",
                        "thresholdWarning": 350.0,
                        "thresholdAlarm": 400.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_020",
                        "pointName": "点位8",
                        "pointCode": "POINT_020",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-300",
                        "position": "汽包",
                        "status": "normal",
                        "currentValue": 1.8,
                        "unit": "MPa",
                        "thresholdWarning": 2.0,
                        "thresholdAlarm": 2.5,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_021",
                        "pointName": "点位9",
                        "pointCode": "POINT_021",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "引风机",
                        "status": "normal",
                        "currentValue": 6.2,
                        "unit": "mm/s",
                        "thresholdWarning": 8.0,
                        "thresholdAlarm": 12.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      },
                      {
                        "pointId": "point_022",
                        "pointName": "点位10",
                        "pointCode": "POINT_022",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "排烟口",
                        "status": "normal",
                        "currentValue": 156.4,
                        "unit": "°C",
                        "thresholdWarning": 160.0,
                        "thresholdAlarm": 180.0,
                        "lastUpdateTime": "2025-12-12 12:05:00"
                      }
                    ]
                  }
                ]
              },
              {
                "workshopId": "workshop_003",
                "workshopName": "车间C",
                "workshopCode": "WORKSHOP_C",
                "status": "warning",
                "deviceCount": 2,
                "pointCount": 4,
                "onlineCount": 1,
                "alarmCount": 1,
                "devices": [
                  {
                    "deviceId": "device_007",
                    "deviceName": "设备g",
                    "deviceCode": "DEV_C_001",
                    "deviceType": "valve",
                    "deviceTypeName": "阀门",
                    "status": "warning",
                    "onlineStatus": "online",
                    "model": "VALVE-200",
                    "manufacturer": "厂家F",
                    "lastDataTime": "2025-12-12 12:04:00",
                    "points": [
                      {
                        "pointId": "point_015",
                        "pointName": "点位1",
                        "pointCode": "POINT_015",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-100",
                        "position": "进口",
                        "status": "warning",
                        "currentValue": 125.8,
                        "unit": "m³/h",
                        "thresholdWarning": 120.0,
                        "thresholdAlarm": 130.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_016",
                        "pointName": "点位2",
                        "pointCode": "POINT_016",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-150",
                        "position": "出口",
                        "status": "normal",
                        "currentValue": 0.45,
                        "unit": "MPa",
                        "thresholdWarning": 0.5,
                        "thresholdAlarm": 0.6,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_017",
                        "pointName": "点位3",
                        "pointCode": "POINT_017",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "阀体",
                        "status": "normal",
                        "currentValue": 45.2,
                        "unit": "°C",
                        "thresholdWarning": 50.0,
                        "thresholdAlarm": 60.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_018",
                        "pointName": "点位4",
                        "pointCode": "POINT_018",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "阀杆",
                        "status": "normal",
                        "currentValue": 2.8,
                        "unit": "mm/s",
                        "thresholdWarning": 4.0,
                        "thresholdAlarm": 6.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_019",
                        "pointName": "点位5",
                        "pointCode": "POINT_019",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "阀门",
                        "status": "warning",
                        "currentValue": 78.5,
                        "unit": "dB",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_020",
                        "pointName": "点位6",
                        "pointCode": "POINT_020",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "周围环境",
                        "status": "normal",
                        "currentValue": 42.8,
                        "unit": "%RH",
                        "thresholdWarning": 50.0,
                        "thresholdAlarm": 60.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_021",
                        "pointName": "点位7",
                        "pointCode": "POINT_021",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-200",
                        "position": "旁路",
                        "status": "normal",
                        "currentValue": 1.8,
                        "unit": "MPa",
                        "thresholdWarning": 2.0,
                        "thresholdAlarm": 2.3,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_022",
                        "pointName": "点位8",
                        "pointCode": "POINT_022",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-200",
                        "position": "旁通管路",
                        "status": "normal",
                        "currentValue": 110.5,
                        "unit": "m³/h",
                        "thresholdWarning": 115.0,
                        "thresholdAlarm": 125.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_023",
                        "pointName": "点位9",
                        "pointCode": "POINT_023",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-250",
                        "position": "密封件",
                        "status": "normal",
                        "currentValue": 52.3,
                        "unit": "°C",
                        "thresholdWarning": 55.0,
                        "thresholdAlarm": 65.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      },
                      {
                        "pointId": "point_024",
                        "pointName": "点位10",
                        "pointCode": "POINT_024",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "执行机构",
                        "status": "normal",
                        "currentValue": 3.2,
                        "unit": "mm/s",
                        "thresholdWarning": 4.0,
                        "thresholdAlarm": 6.0,
                        "lastUpdateTime": "2025-12-12 12:04:00"
                      }
                    ]
                  },
                  {
                    "deviceId": "device_008",
                    "deviceName": "设备h",
                    "deviceCode": "DEV_C_002",
                    "deviceType": "mixer",
                    "deviceTypeName": "搅拌器",
                    "status": "normal",
                    "onlineStatus": "offline",
                    "model": "MIX-400",
                    "manufacturer": "厂家G",
                    "lastDataTime": "2025-12-12 12:03:00",
                    "points": [
                      {
                        "pointId": "point_017",
                        "pointName": "点位1",
                        "pointCode": "POINT_017",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-180",
                        "position": "搅拌轴",
                        "status": "normal",
                        "currentValue": 3.2,
                        "unit": "mm/s",
                        "thresholdWarning": 4.0,
                        "thresholdAlarm": 6.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_018",
                        "pointName": "点位2",
                        "pointCode": "POINT_018",
                        "pointType": "torque",
                        "pointTypeName": "扭矩监测点",
                        "sensorModel": "TS-200",
                        "position": "减速机输出轴",
                        "status": "normal",
                        "currentValue": 1200,
                        "unit": "Nm",
                        "thresholdWarning": 1300,
                        "thresholdAlarm": 1500,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_019",
                        "pointName": "点位3",
                        "pointCode": "POINT_019",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "电机",
                        "status": "normal",
                        "currentValue": 68.5,
                        "unit": "°C",
                        "thresholdWarning": 75.0,
                        "thresholdAlarm": 85.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_020",
                        "pointName": "点位4",
                        "pointCode": "POINT_020",
                        "pointType": "speed",
                        "pointTypeName": "转速监测点",
                        "sensorModel": "SS-150",
                        "position": "搅拌轴",
                        "status": "normal",
                        "currentValue": 85.2,
                        "unit": "rpm",
                        "thresholdWarning": 90.0,
                        "thresholdAlarm": 100.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_021",
                        "pointName": "点位5",
                        "pointCode": "POINT_021",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-150",
                        "position": "搅拌罐",
                        "status": "normal",
                        "currentValue": 0.25,
                        "unit": "MPa",
                        "thresholdWarning": 0.3,
                        "thresholdAlarm": 0.4,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_022",
                        "pointName": "点位6",
                        "pointCode": "POINT_022",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "减速机",
                        "status": "warning",
                        "currentValue": 5.8,
                        "unit": "mm/s",
                        "thresholdWarning": 5.0,
                        "thresholdAlarm": 7.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_023",
                        "pointName": "点位7",
                        "pointCode": "POINT_023",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-200",
                        "position": "搅拌罐",
                        "status": "normal",
                        "currentValue": 75.6,
                        "unit": "dB",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_024",
                        "pointName": "点位8",
                        "pointCode": "POINT_024",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "周围环境",
                        "status": "normal",
                        "currentValue": 48.3,
                        "unit": "%RH",
                        "thresholdWarning": 55.0,
                        "thresholdAlarm": 65.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_025",
                        "pointName": "点位9",
                        "pointCode": "POINT_025",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-250",
                        "position": "搅拌物料",
                        "status": "normal",
                        "currentValue": 42.8,
                        "unit": "°C",
                        "thresholdWarning": 45.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      },
                      {
                        "pointId": "point_026",
                        "pointName": "点位10",
                        "pointCode": "POINT_026",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "支撑架",
                        "status": "normal",
                        "currentValue": 2.1,
                        "unit": "mm/s",
                        "thresholdWarning": 3.0,
                        "thresholdAlarm": 5.0,
                        "lastUpdateTime": "2025-12-12 12:03:00"
                      }
                    ]
                  }
                ]
              },
              {
                "workshopId": "workshop_004",
                "workshopName": "车间D",
                "workshopCode": "WORKSHOP_D",
                "status": "normal",
                "deviceCount": 2,
                "pointCount": 4,
                "onlineCount": 2,
                "alarmCount": 0,
                "devices": [
                  {
                    "deviceId": "device_009",
                    "deviceName": "设备i",
                    "deviceCode": "DEV_D_001",
                    "deviceType": "tank",
                    "deviceTypeName": "储罐",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "TANK-500",
                    "manufacturer": "厂家H",
                    "lastDataTime": "2025-12-12 12:02:00",
                    "points": [
                      {
                        "pointId": "point_019",
                        "pointName": "点位1",
                        "pointCode": "POINT_019",
                        "pointType": "level",
                        "pointTypeName": "液位监测点",
                        "sensorModel": "LS-100",
                        "position": "顶部",
                        "status": "normal",
                        "currentValue": 2.5,
                        "unit": "m",
                        "thresholdWarning": 2.7,
                        "thresholdAlarm": 3.0,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_020",
                        "pointName": "点位2",
                        "pointCode": "POINT_020",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-150",
                        "position": "中部",
                        "status": "normal",
                        "currentValue": 35.6,
                        "unit": "°C",
                        "thresholdWarning": 40.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_021",
                        "pointName": "点位3",
                        "pointCode": "POINT_021",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-200",
                        "position": "底部",
                        "status": "normal",
                        "currentValue": 0.35,
                        "unit": "MPa",
                        "thresholdWarning": 0.4,
                        "thresholdAlarm": 0.5,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_022",
                        "pointName": "点位4",
                        "pointCode": "POINT_022",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "罐壁",
                        "status": "normal",
                        "currentValue": 1.2,
                        "unit": "mm/s",
                        "thresholdWarning": 2.0,
                        "thresholdAlarm": 3.0,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_023",
                        "pointName": "点位5",
                        "pointCode": "POINT_023",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-150",
                        "position": "外部",
                        "status": "warning",
                        "currentValue": 72.8,
                        "unit": "dB",
                        "thresholdWarning": 70.0,
                        "thresholdAlarm": 80.0,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_024",
                        "pointName": "点位6",
                        "pointCode": "POINT_024",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-600",
                        "position": "内部",
                        "status": "normal",
                        "currentValue": 38.5,
                        "unit": "%RH",
                        "thresholdWarning": 45.0,
                        "thresholdAlarm": 55.0,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_025",
                        "pointName": "点位7",
                        "pointCode": "POINT_025",
                        "pointType": "conductivity",
                        "pointTypeName": "电导率监测点",
                        "sensorModel": "CS-300",
                        "position": "内部",
                        "status": "normal",
                        "currentValue": 1500,
                        "unit": "μS/cm",
                        "thresholdWarning": 1600,
                        "thresholdAlarm": 1800,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_026",
                        "pointName": "点位8",
                        "pointCode": "POINT_026",
                        "pointType": "ph",
                        "pointTypeName": "pH监测点",
                        "sensorModel": "PHS-400",
                        "position": "内部",
                        "status": "normal",
                        "currentValue": 7.2,
                        "unit": "pH",
                        "thresholdWarning": 7.0,
                        "thresholdAlarm": 6.5,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_027",
                        "pointName": "点位9",
                        "pointCode": "POINT_027",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "罐底",
                        "status": "normal",
                        "currentValue": 32.4,
                        "unit": "°C",
                        "thresholdWarning": 35.0,
                        "thresholdAlarm": 40.0,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      },
                      {
                        "pointId": "point_028",
                        "pointName": "点位10",
                        "pointCode": "POINT_028",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "支撑脚",
                        "status": "normal",
                        "currentValue": 0.8,
                        "unit": "mm/s",
                        "thresholdWarning": 1.0,
                        "thresholdAlarm": 1.5,
                        "lastUpdateTime": "2025-12-12 12:02:00"
                      }
                    ]
                  },
                  {
                    "deviceId": "device_010",
                    "deviceName": "设备j",
                    "deviceCode": "DEV_D_002",
                    "deviceType": "reactor",
                    "deviceTypeName": "反应釜",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "REAC-600",
                    "manufacturer": "厂家I",
                    "lastDataTime": "2025-12-12 12:01:00",
                    "points": [
                      {
                        "pointId": "point_021",
                        "pointName": "点位1",
                        "pointCode": "POINT_021",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-200",
                        "position": "内壁",
                        "status": "normal",
                        "currentValue": 185.2,
                        "unit": "°C",
                        "thresholdWarning": 190.0,
                        "thresholdAlarm": 200.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_022",
                        "pointName": "点位2",
                        "pointCode": "POINT_022",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-180",
                        "position": "顶部",
                        "status": "normal",
                        "currentValue": 0.85,
                        "unit": "MPa",
                        "thresholdWarning": 0.9,
                        "thresholdAlarm": 1.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_023",
                        "pointName": "点位3",
                        "pointCode": "POINT_023",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-100",
                        "position": "搅拌轴",
                        "status": "normal",
                        "currentValue": 2.5,
                        "unit": "mm/s",
                        "thresholdWarning": 3.0,
                        "thresholdAlarm": 4.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_024",
                        "pointName": "点位4",
                        "pointCode": "POINT_024",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-250",
                        "position": "夹套",
                        "status": "warning",
                        "currentValue": 195.8,
                        "unit": "°C",
                        "thresholdWarning": 190.0,
                        "thresholdAlarm": 200.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_025",
                        "pointName": "点位5",
                        "pointCode": "POINT_025",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-300",
                        "position": "底部",
                        "status": "normal",
                        "currentValue": 0.75,
                        "unit": "MPa",
                        "thresholdWarning": 0.8,
                        "thresholdAlarm": 0.9,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_026",
                        "pointName": "点位6",
                        "pointCode": "POINT_026",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "支撑架",
                        "status": "normal",
                        "currentValue": 1.8,
                        "unit": "mm/s",
                        "thresholdWarning": 2.5,
                        "thresholdAlarm": 3.5,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_027",
                        "pointName": "点位7",
                        "pointCode": "POINT_027",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "AS-200",
                        "position": "外壁",
                        "status": "normal",
                        "currentValue": 78.3,
                        "unit": "dB",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_028",
                        "pointName": "点位8",
                        "pointCode": "POINT_028",
                        "pointType": "level",
                        "pointTypeName": "液位监测点",
                        "sensorModel": "LS-150",
                        "position": "侧壁",
                        "status": "normal",
                        "currentValue": 3.2,
                        "unit": "m",
                        "thresholdWarning": 3.5,
                        "thresholdAlarm": 4.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_029",
                        "pointName": "点位9",
                        "pointCode": "POINT_029",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-300",
                        "position": "出料口",
                        "status": "normal",
                        "currentValue": 175.6,
                        "unit": "°C",
                        "thresholdWarning": 180.0,
                        "thresholdAlarm": 190.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      },
                      {
                        "pointId": "point_030",
                        "pointName": "点位10",
                        "pointCode": "POINT_030",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-150",
                        "position": "进料口",
                        "status": "normal",
                        "currentValue": 1.5,
                        "unit": "mm/s",
                        "thresholdWarning": 2.0,
                        "thresholdAlarm": 3.0,
                        "lastUpdateTime": "2025-12-12 12:01:00"
                      }
                    ]
                  }
                ]
              },
              {
                "workshopId": "workshop_005",
                "workshopName": "车间E",
                "workshopCode": "WORKSHOP_E",
                "status": "normal",
                "deviceCount": 2,
                "pointCount": 4,
                "onlineCount": 2,
                "alarmCount": 1,
                "devices": [
                  {
                    "deviceId": "device_011",
                    "deviceName": "设备k",
                    "deviceCode": "DEV_E_001",
                    "deviceType": "filter",
                    "deviceTypeName": "过滤器",
                    "status": "alarm",
                    "onlineStatus": "online",
                    "model": "FILT-300",
                    "manufacturer": "厂家J",
                    "lastDataTime": "2025-12-12 12:00:00",
                    "points": [
                      {
                        "pointId": "point_023",
                        "pointName": "点位1",
                        "pointCode": "POINT_023",
                        "pointType": "pressure",
                        "pointTypeName": "压差监测点",
                        "sensorModel": "PS-120",
                        "position": "进出口",
                        "status": "alarm",
                        "currentValue": 0.18,
                        "unit": "MPa",
                        "thresholdWarning": 0.1,
                        "thresholdAlarm": 0.15,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_024",
                        "pointName": "点位2",
                        "pointCode": "POINT_024",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-150",
                        "position": "出口",
                        "status": "normal",
                        "currentValue": 85.4,
                        "unit": "m³/h",
                        "thresholdWarning": 90.0,
                        "thresholdAlarm": 100.0,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_027",
                        "pointName": "点位3",
                        "pointCode": "POINT_027",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "顶部",
                        "status": "normal",
                        "currentValue": 2.1,
                        "unit": "mm/s",
                        "thresholdWarning": 3.5,
                        "thresholdAlarm": 5.0,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_028",
                        "pointName": "点位4",
                        "pointCode": "POINT_028",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-100",
                        "position": "内部",
                        "status": "normal",
                        "currentValue": 45.2,
                        "unit": "%RH",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 70.0,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_029",
                        "pointName": "点位5",
                        "pointCode": "POINT_029",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-180",
                        "position": "中部",
                        "status": "warning",
                        "currentValue": 48.7,
                        "unit": "°C",
                        "thresholdWarning": 45.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_030",
                        "pointName": "点位6",
                        "pointCode": "POINT_030",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-120",
                        "position": "进口",
                        "status": "normal",
                        "currentValue": 0.25,
                        "unit": "MPa",
                        "thresholdWarning": 0.3,
                        "thresholdAlarm": 0.35,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_031",
                        "pointName": "点位7",
                        "pointCode": "POINT_031",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-150",
                        "position": "入口",
                        "status": "normal",
                        "currentValue": 78.3,
                        "unit": "m³/h",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_032",
                        "pointName": "点位8",
                        "pointCode": "POINT_032",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "SS-300",
                        "position": "外壳",
                        "status": "normal",
                        "currentValue": 65.2,
                        "unit": "dB",
                        "thresholdWarning": 70.0,
                        "thresholdAlarm": 75.0,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_033",
                        "pointName": "点位9",
                        "pointCode": "POINT_033",
                        "pointType": "speed",
                        "pointTypeName": "转速监测点",
                        "sensorModel": "SP-400",
                        "position": "驱动端",
                        "status": "normal",
                        "currentValue": 1480,
                        "unit": "rpm",
                        "thresholdWarning": 1500,
                        "thresholdAlarm": 1600,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      },
                      {
                        "pointId": "point_034",
                        "pointName": "点位10",
                        "pointCode": "POINT_034",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "底部",
                        "status": "alarm",
                        "currentValue": 5.8,
                        "unit": "mm/s",
                        "thresholdWarning": 3.5,
                        "thresholdAlarm": 5.0,
                        "lastUpdateTime": "2025-12-12 12:00:00"
                      }
                    ]
                  },
                  {
                    "deviceId": "device_012",
                    "deviceName": "设备l",
                    "deviceCode": "DEV_E_002",
                    "deviceType": "cooler",
                    "deviceTypeName": "冷却器",
                    "status": "normal",
                    "onlineStatus": "online",
                    "model": "COOL-400",
                    "manufacturer": "厂家K",
                    "lastDataTime": "2025-12-12 11:59:00",
                    "points": [
                      {
                        "pointId": "point_025",
                        "pointName": "点位1",
                        "pointCode": "POINT_025",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-180",
                        "position": "入口",
                        "status": "normal",
                        "currentValue": 75.2,
                        "unit": "°C",
                        "thresholdWarning": 80.0,
                        "thresholdAlarm": 90.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_026",
                        "pointName": "点位2",
                        "pointCode": "POINT_026",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-180",
                        "position": "出口",
                        "status": "normal",
                        "currentValue": 42.6,
                        "unit": "°C",
                        "thresholdWarning": 45.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_035",
                        "pointName": "点位3",
                        "pointCode": "POINT_035",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "顶部",
                        "status": "normal",
                        "currentValue": 1.8,
                        "unit": "mm/s",
                        "thresholdWarning": 3.5,
                        "thresholdAlarm": 5.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_036",
                        "pointName": "点位4",
                        "pointCode": "POINT_036",
                        "pointType": "humidity",
                        "pointTypeName": "湿度监测点",
                        "sensorModel": "HS-100",
                        "position": "内部",
                        "status": "normal",
                        "currentValue": 48.5,
                        "unit": "%RH",
                        "thresholdWarning": 60.0,
                        "thresholdAlarm": 70.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_037",
                        "pointName": "点位5",
                        "pointCode": "POINT_037",
                        "pointType": "pressure",
                        "pointTypeName": "压力监测点",
                        "sensorModel": "PS-120",
                        "position": "进口",
                        "status": "normal",
                        "currentValue": 0.22,
                        "unit": "MPa",
                        "thresholdWarning": 0.3,
                        "thresholdAlarm": 0.35,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_038",
                        "pointName": "点位6",
                        "pointCode": "POINT_038",
                        "pointType": "flow",
                        "pointTypeName": "流量监测点",
                        "sensorModel": "FS-150",
                        "position": "出口",
                        "status": "normal",
                        "currentValue": 82.1,
                        "unit": "m³/h",
                        "thresholdWarning": 90.0,
                        "thresholdAlarm": 100.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_039",
                        "pointName": "点位7",
                        "pointCode": "POINT_039",
                        "pointType": "sound",
                        "pointTypeName": "声音监测点",
                        "sensorModel": "SS-300",
                        "position": "外壳",
                        "status": "warning",
                        "currentValue": 72.5,
                        "unit": "dB",
                        "thresholdWarning": 70.0,
                        "thresholdAlarm": 75.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_040",
                        "pointName": "点位8",
                        "pointCode": "POINT_040",
                        "pointType": "speed",
                        "pointTypeName": "转速监测点",
                        "sensorModel": "SP-400",
                        "position": "驱动端",
                        "status": "normal",
                        "currentValue": 1450,
                        "unit": "rpm",
                        "thresholdWarning": 1500,
                        "thresholdAlarm": 1600,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_041",
                        "pointName": "点位9",
                        "pointCode": "POINT_041",
                        "pointType": "temperature",
                        "pointTypeName": "温度监测点",
                        "sensorModel": "TS-180",
                        "position": "中部",
                        "status": "alarm",
                        "currentValue": 52.3,
                        "unit": "°C",
                        "thresholdWarning": 45.0,
                        "thresholdAlarm": 50.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      },
                      {
                        "pointId": "point_042",
                        "pointName": "点位10",
                        "pointCode": "POINT_042",
                        "pointType": "vibration",
                        "pointTypeName": "振动监测点",
                        "sensorModel": "VS-200",
                        "position": "底部",
                        "status": "alarm",
                        "currentValue": 5.5,
                        "unit": "mm/s",
                        "thresholdWarning": 3.5,
                        "thresholdAlarm": 5.0,
                        "lastUpdateTime": "2025-12-12 11:59:00"
                      }
                    ]
                  },
                ]
              }
            ]
          }
        ],
        "statistics": {
          "totalFactoryCount": 1,
          "totalWorkshopCount": 5,
          "totalDeviceCount": 12,
          "totalPointCount": 120,
          "onlineDeviceCount": 12,
          "offlineDeviceCount": 0,
          "alarmDeviceCount": 2,
          "warningDeviceCount": 1,
          "normalDeviceCount": 9
        }
      },
      "timestamp": 1769483993153
    };
    
    // 将假数据转换为前端所需格式
    const transformedData = transformDeviceTreeData(mockData);
    deviceTreeData.value = transformedData;
  };
  
  // 初始化时加载假数据
  initializeDeviceTreeData();

  // 当前选中的设备ID
  const selectedDeviceId = ref<string | null>(null)

  // 展开的节点
  const expandedKeys = ref<string[]>(['factory-1'])

  // 设置选中的设备ID
  const setSelectedDeviceId = (id: string | null) => {
    selectedDeviceId.value = id
  }

  // 设置展开的节点
  const setExpandedKeys = (keys: string[]) => {
    expandedKeys.value = keys
  }

  // 重置设备树到初始状态
  const resetDeviceTreeState = () => {
    selectedDeviceId.value = null
    expandedKeys.value = ['factory-1']  // 默认展开第一个工厂节点
  }

  // 获取默认展开的第一个车间ID
  const getDefaultWorkshopId = (): string | null => {
    const factory = deviceTreeData.value[0]
    if (factory && factory.children && factory.children.length > 0) {
      const firstChild = factory.children[0]
      return firstChild ? firstChild.id || null : null
    }
    return null
  }

  return {
    deviceTreeData,
    selectedDeviceId,
    expandedKeys,
    setSelectedDeviceId,
    setExpandedKeys,
    resetDeviceTreeState,
    getDefaultWorkshopId
  }
})